# typed: false
# frozen_string_literal: true

# Generated by apps/bridge/scripts/gen-formula.ts — do not edit by hand.
class Rein < Formula
  desc "Remote-control your local AI coding harnesses from your phone"
  homepage "https://rein.build"
  version "0.1.23"

  on_macos do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.23/rein-darwin-arm64.tar.gz"
      sha256 "4e8b77636a32f1f7ba9eb1027418613cc3e27f8ef6ddf9cf0c16607abed3563f"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.23/rein-darwin-x64.tar.gz"
      sha256 "6e8cb95f910916a706ad839fbdddc6395b5084833562a8d88c0fb8a4e291035e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.23/rein-linux-arm64.tar.gz"
      sha256 "d801e2bd86c260558ffd3a5529a416721b5250c72c12c20ab6cba406c8ca8a41"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.23/rein-linux-x64.tar.gz"
      sha256 "54ddaefe7b73f11f2302604bd5b287757f3e4ffe96d7418f78c9290ac50158f2"
    end
  end

  def install
    # Keep the binary + native sidecars (pty.node, node_datachannel.node,
    # spawn-helper) as siblings — the runtime loader resolves them via the
    # binary's own directory.
    libexec.install Dir["*"]
    # Tell 'rein update' this install is Homebrew-managed so it defers to
    # 'brew upgrade rein' instead of clobbering the Cellar.
    (libexec/".rein-managed-by").write "homebrew\n"
    bin.install_symlink libexec/"rein"
  end

  service do
    run [opt_libexec/"rein", "__daemon"]
    keep_alive false
    log_path "#{Dir.home}/.reins/bridge.log"
    error_log_path "#{Dir.home}/.reins/bridge.log"
  end

  def caveats
    <<~EOS
      Pair with the Rein app:
        rein login        # link this machine to your account
        rein start        # or: brew services start rein
        rein setup        # show the pairing QR / code

      Upgrades are managed by Homebrew — run 'brew upgrade rein'.
      (The bundled 'rein update' is disabled for Homebrew installs.)

      The macOS desktop app installs its own bridge separately; use one or the
      other on a given machine.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rein version")
  end
end
