# typed: false
# frozen_string_literal: true

# Generated by apps/bridge/scripts/gen-formula.ts — do not edit by hand.
class Rein < Formula
  desc "Remote-control your local AI coding harnesses from your phone"
  homepage "https://rein.build"
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.4/rein-darwin-arm64.tar.gz"
      sha256 "8a7f4d3ac420c81a66c02d4b5db04d6ff90a6b5f3cbd9546a539aabd8feb5f2a"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.4/rein-darwin-x64.tar.gz"
      sha256 "e08eb6e3ce0bc127bdf52dbf771187bae0b2f9e991d67da493be670808756d2f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.4/rein-linux-arm64.tar.gz"
      sha256 "8d244d16d434b4ad04da9fa8ab364014738ea424ff14f415cdcbde4cb7ef1a1b"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.4/rein-linux-x64.tar.gz"
      sha256 "a89c6d83c0930b343df079dadc14e74bc89fd097a03c04de5055d9226173b4af"
    end
  end

  def install
    # Keep the binary + native sidecars (pty.node, node_datachannel.node,
    # spawn-helper) as siblings — the runtime loader resolves them via the
    # binary's own directory.
    libexec.install Dir["*"]
    # Tell 'rein update' this install is Homebrew-managed so it defers to
    # 'brew upgrade rein' instead of clobbering the Cellar.
    (libexec/".rein-managed-by").write "homebrew\n"
    bin.install_symlink libexec/"rein"
  end

  service do
    run [opt_libexec/"rein", "__daemon"]
    keep_alive false
    log_path "#{Dir.home}/.reins/bridge.log"
    error_log_path "#{Dir.home}/.reins/bridge.log"
  end

  def caveats
    <<~EOS
      Pair with the Rein app:
        rein login        # link this machine to your account
        rein start        # or: brew services start rein
        rein token        # show the pairing QR / code

      Upgrades are managed by Homebrew — run 'brew upgrade rein'.
      (The bundled 'rein update' is disabled for Homebrew installs.)

      The macOS desktop app installs its own bridge separately; use one or the
      other on a given machine.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rein version")
  end
end
