# typed: false
# frozen_string_literal: true

# Generated by apps/bridge/scripts/gen-formula.ts — do not edit by hand.
class Rein < Formula
  desc "Remote-control your local AI coding harnesses from your phone"
  homepage "https://rein.build"
  version "0.1.38"

  on_macos do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.38/rein-darwin-arm64.tar.gz"
      sha256 "0e199da71a09b08e8bb4e38500ba148f62dc8e358fb9510404e9a8d5c7054759"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.38/rein-darwin-x64.tar.gz"
      sha256 "7db3e57d795fa1a4e4a78e6f295359afea9b71366d6ac413749eac5e58e3fa47"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.38/rein-linux-arm64.tar.gz"
      sha256 "cbbf2a68bbc96f47fe6f4f73adc76617ae6af4261b87c1efb7970096f158001b"
    end
    on_intel do
      url "https://github.com/rein-industries/rein/releases/download/v0.1.38/rein-linux-x64.tar.gz"
      sha256 "b8601ad3a3592ff50783510b6c62ab8368e0e1ce8f3fadc5d97a3b01bdb7b173"
    end
  end

  def install
    # Keep the binary + native sidecars (pty.node, node_datachannel.node,
    # spawn-helper) as siblings — the runtime loader resolves them via the
    # binary's own directory.
    libexec.install Dir["*"]
    # Tell 'rein update' this install is Homebrew-managed so it defers to
    # 'brew upgrade rein' instead of clobbering the Cellar.
    (libexec/".rein-managed-by").write "homebrew\n"
    bin.install_symlink libexec/"rein"
  end

  service do
    run [opt_libexec/"rein", "__daemon"]
    keep_alive false
    log_path "#{Dir.home}/.reins/bridge.log"
    error_log_path "#{Dir.home}/.reins/bridge.log"
  end

  def caveats
    <<~EOS
      Pair with the Rein app:
        rein login        # link this machine to your account
        rein start        # or: brew services start rein
        rein setup        # show the pairing QR / code

      Upgrades are managed by Homebrew — run 'brew upgrade rein'.
      (The bundled 'rein update' is disabled for Homebrew installs.)

      The macOS desktop app installs its own bridge separately; use one or the
      other on a given machine.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rein version")
  end
end
